### ISSUE TITLE
switch gets stuck with other modules on nintendo switch logo

### ISSUE THREAD

**Issue by twinec** [jonyluke/SlideNX#1]
i installed this on my switch, configured the ini (via ftpd), rebooted the switch to find it was stuck on the nintendo switch logo. HELP! EDIT: It works without any other modules. try adding support for other modules

**Comment by jonyluke** [comment]
Don't worry it is probably because you don't configure correctly the ini, just extract the files in the root of the sd

**Comment by twinec** [comment]
did that, rebooted, keeps happening

**Comment by jonyluke** [comment]
I just installed it again and it starts without problems

**Comment by jonyluke** [comment]
It does not find you
jonyluke#6811

**Comment by twinec** [comment]
update: it works without sysftpd. try adding compatibility with other modules because it gets stuck on the switch logo with other modules

**Comment by jonyluke** [comment]
I will look that

**Comment by jonyluke** [comment]
As version 0.16 this should be now fixed.
